#!/bin/bash

# Script to run docker-compose with proper user ownership
# This ensures all files generated by the migrator are owned by the current user

# Get current user's UID and GID
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)

# Set the environment variables for docker-compose
# Some systems have readonly UID/GID, so we handle this gracefully
{
    export UID=$CURRENT_UID
    export GID=$CURRENT_GID
} 2>/dev/null

echo "Setting up Docker containers with UID=$CURRENT_UID and GID=$CURRENT_GID"

# Ensure required directories exist with correct permissions
# These directories are mounted as volumes and need to be writable by the container
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

for dir in logs output cws; do
    mkdir -p "$PROJECT_ROOT/$dir"
    chmod 755 "$PROJECT_ROOT/$dir"
done

echo "Created/verified directories: logs, output, cws"

# Pass all arguments to docker-compose
exec docker-compose "$@"